### ISSUE TITLE
create new geojson dataset from upload

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#101]
This may be the trickiest part of this milestone.  

Do we allow the user to upload a file, then after the item is created, if the type of file is geojson, "upgrade" the item to a geojson dataset?  If so, need to ensure the endpoint created in #99 can handle that.  

Or should we add an additional UI step asking the user what kind of file they've uploaded, and if they select geojson, at that point upgrade the item to a geojson dataset?

Also, how to handle cases of pushing up multiple files, and other possible boundary conditions?

**Comment by aashish24** [comment]
If the file they are uploading has .geojson extension, then we should automatically create geojson dataset (https://en.wikipedia.org/wiki/GeoJSON). If it is a general format (json) then I think it would nice if have a list of formats (geojson would be one of them) that we can present to the user.

**Comment by jbeezley** [comment]
There is a MIME type for geojson, [vnd.geo+json](http://www.iana.org/assignments/media-types/application/vnd.geo+json).  It lists both `.json` and `.geojson` extensions.  I'm still not sure what you mean by a general format json file; there is no standard for it.  My preference would be to default to geojson for any `.json` file and have an "advanced" button of some kind where you can provide the appropriate json paths to the coordinates.

**Comment by aashish24** [comment]
> There is a MIME type for geojson, vnd.geo+json. It lists both .json and .geojson extensions. I'm still not sure what you mean by a general format json file; there is no standard for it. My preference would be to default to geojson for any .json file and have an "advanced" button of some kind where you can provide the appropriate json paths to the coordinates.

I am good with this. So if mime type is set or file has extension .geojson then it should be pretty obvious what we have to do. All other cases, your mapping option could be utilized.

**Comment by aashish24** [comment]
this is done now.
