### ISSUE TITLE
update ansible readme

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#102]
The formatting is a bit off when displayed as RST in GitHub, specifically on the sections where commands are issued.  

https://github.com/Kitware/minerva/tree/2a2d6c7cc9ffa51ae1714b23ce7c9f6a6da1eeba/data_services/deploy/ansible

**Comment by aashish24** [comment]
@mgrauer I just realized that as well.  I will fix it. Actually, I prefer MD vs RST format because I am more familiar with the former.

**Comment by mgrauer** [comment]
:+1:  for MD
