### ISSUE TITLE
Clarify client/server/services in Readme

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#111]
As this repo is getting more complex, we should standardize on some terms and clean up the Readme.

    client: the web client of Minerva, written in Backbone.js
    server: the server side Rest endpoints of Minerva, written in Python, based on Girder
    services: the set of services that host and process datasets, including
        * Geonode/Geoserver stack
        * Celery tasks for downloading and processing data
        * Geonode templates for specific tasks
        * Provisioning scripts with Ansible

**Comment by aashish24** [comment]
:+1: thanks for writing this up. I am updating the README as well.

**Comment by mgrauer** [comment]
@mbertrand @jbeezley You two might have more to say here, in case I'm missing something obvious.  Or maybe you two can contribute later to the README once your current data services work is complete.

**Comment by jbeezley** [comment]
It does seem to me that the definition of "data" is a bit broad.  I think the first three might qualify as services.  In many cases, the minerva server acts as a proxy to other services. 

The ansible playbooks I would probably put in a different category.  Maybe "deployment"?

**Comment by jbeezley** [comment]
I also noticed earlier today that the repository description just says "minerva".  We should come up with a short tag line to put there.

**Comment by mgrauer** [comment]
Thanks for the note about the short tag.  I changed it to

    Minerva: web application for geospatial analysis and visualization

and am happy for someone with a stronger opinion to change it further.

**Comment by aashish24** [comment]
@jbeezley @mgrauer I am working on updating the README so please wait until then. One another thing I am adding is licensing and shared ownership with Epidemico.

**Comment by aashish24** [comment]
client/server/data is short form. I agree that in its complete description it would be:
client (UI and visualization)/ server (analysis and proxy to other serivces) / data services.

**Comment by jbeezley** [comment]
I would suggest just "services" for a short form.  I wouldn't think of any of those as data.

**Comment by aashish24** [comment]
client/server/services sounds good to me. @mgrauer @mbertrand  what you guys think?

**Comment by mgrauer** [comment]
great :tiger:

**Comment by aashish24** [comment]
We have updated the READMe. I am closing this now.
