### ISSUE TITLE
change defaults of folder search methods in minerva_utility to create=True

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#114]
Currently the default for finding the named folders in the minerva_utility methods is create=False, which means no folder will be created if one isn't found.  This should be changed to True, so that e.g., when a user creates a Dataset they will have a user/minerva/dataset folder.  

If the system allows them to register a user, they should probably be allowed to create datasets and sources.

If we want to prevent users from taking up resources, that can be handled in quotas or preventing them from registering.  The current default will just cause new users to have normal minerva operations fail.

**Comment by matthewma7** [comment]
Current Minerva has been implemented as described.
