### ISSUE TITLE
404 query params error when creating WMS layer

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#121]
I've seen this as a fleeting error a few times, it always seems to resolve itself as soon as I try again, and I haven't got the details down yet.  

Sometimes when a WMS source exists and you try to create a new layer from that source, there is a 404 query params error.  I've seen it with Flood Detection/Intensity, but that may just be because it is what I was playing with recently.

@essamjoubori  @mbertrand Please be on the lookout and if you see it provide more details.

:eyes:

**Comment by mgrauer** [comment]
http://localhost:8080/?Proportion+of+Outpatient+Malaria+Visits=on#session/5602eaaf0640fd0634293a71

Unexpected query string parameters: Proportion of Outpatient Malaria Visits


Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
http://localhost:8080/?Proportion+of+Outpatient+Malaria+Visits=on#session/5602eaaf0640fd0634293a71 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by mbertrand** [comment]
@mgrauer I noticed this too today, will look into it
