### ISSUE TITLE
Use better WMTS for default map view

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#137]

**Comment by mbertrand** [comment]
Some options:

MapQuest: http://otile1.mqcdn.com/tiles/1.0.0/map/X/Y/Z.png
![example](http://otile1.mqcdn.com/tiles/1.0.0/map/12/656/1580.png)

Stamen Toner: http://d.tile.stamen.com/toner/X/Y/Z.png
![example](http://d.tile.stamen.com/toner/12/656/1580.png)

Stamen Watercolor: http://a.tile.stamen.com/watercolor/X/Y/Z.png
![example](http://a.tile.stamen.com/watercolor/12/656/1580.jpg)

**Comment by aashish24** [comment]
@mbertrand I am thinking MapQuest would be best.

**Comment by danlamanna** [comment]
For what it's worth, we've had 2 separate projects that ended up going with the light version of [cartodb base](https://dl.dropboxusercontent.com/u/580074/cartodb_basemaps/index.html#7/42.098/-72.213).

**Comment by matthewma7** [comment]
Minerva is using OpenLayers. Deploy hosted Minerva is using the cartodb base. Close.
