### ISSUE TITLE
have all jobs provide links to job outputs

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#145]
If a job creates a dataset or source or whatever, the job should provide a way of accessing the output, at least by the time the job succeeds.

Something like

```
output_type: [dataset|source]
source_id: id
```

This way, when we listen for the job notifications in the web client, we can load the individual output and add it to the correct collection, rather than refetching the collection, which causes us to lose state.

**Comment by mgrauer** [comment]
I'm going to try namespacing this within the kwargs of the job under minerva, e.g.

```
kwargs = {
    ...
    'minerva': {
        'output_type': 'dataset',
        'dataset_id': dataset['_id']
    }
}
```

**Comment by mgrauer** [comment]
Actually, we should do this under the meta object on the job, in a minerva namespace.

**Comment by mgrauer** [comment]
If a job fails during processing, it should delete whatever resources it is attached to, i.e. a source or dataset that it has created and modified.

**Comment by mgrauer** [comment]
Currently there is a bug where

  * if you have datasets that are currently displayed in the session
  * then you create a new dataset via a job
  * when the job finishes, the dataset collection will be fetched, which erases the `displayed` state in the shown datasets
  * and then if any additional dataset is requested to be shown, the previously shown datasets will continue to be shown in the map panel, but they will disappear from the session panel display

A fix for this is to have the job status listeners on the data and session panel listen for a job success event of the correct type, then--because we will be storing the job output pointer as detailed above--we should load that individual resource model and add it to the appropriate collection type, then rerender the corresponding list panel.  That way the collection won't be fetched, and our new resource will show up in the appropriate list (and we can even do some fancy UI highlighting on the new resource row if desired).

**Comment by aashish24** [comment]
So how its done right now?

**Comment by mgrauer** [comment]
We listen for job status updates on the [Dataset Panel](https://github.com/Kitware/minerva/blob/master/web_external/js/views/body/DataPanel.js#L105-L110) and coming in with #159, the [Source Panel](https://github.com/Kitware/minerva/blob/S3_source_refactor/web_external/js/views/body/SourcePanel.js#L126-L132).  If the job status is `success`, we do a fetch on the dataset/source collection.

**Comment by aashish24** [comment]
> We listen for job status updates on the Dataset Panel and coming in with #159, the Source Panel. If the job status is success, we do a fetch on the dataset/source collection.

Ah, thanks. Can it we made such that we are not relying on panel for this? Since that's a UI component. Is this something we can move to DatasetModel and SourceModel instead?

**Comment by mgrauer** [comment]
That's a good point.  Probably in the collections is the best place.  We need to use the collection "model" method anyway to figure out the correct Model subclass to create.

**Comment by aashish24** [comment]
> collections is the best place

+1 that would work. Should we create an issue for that?

**Comment by mgrauer** [comment]
created

**Comment by matthewma7** [comment]
Outdated. Girder_worker has been rewritten around celery task.
