### ISSUE TITLE
travis failing on npm install of geojs

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#147]
@jbeezley 

This just started showing up.  Travis is failing, but in a way that you can't even get to the build from the PR--on the PR page the build looks like it is running forever.

https://travis-ci.org/Kitware/minerva/builds/84422719

>39.53s$ npm install
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"3.3.7"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"3.3.7"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"3.3.7"})
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g
npm WARN prefer global bower@1.4.1 should be installed with -g
> geojs@0.5.0 postinstall /home/travis/build/girder/plugins/minerva/node_modules/geojs
> bower --quiet install
minerva@0.1.0 /home/travis/build/girder/plugins/minerva
└─┬ JSONPath@0.10.0 
  └── underscore@1.8.3 
npm WARN EPACKAGEJSON minerva@0.1.0 No repository field.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "node" "/home/travis/.nvm/v0.10.36/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v3.3.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno Unknown system errno 7
npm ERR! syscall spawn
npm ERR! geojs@0.5.0 postinstall: `bower --quiet install`
npm ERR! spawn Unknown system errno 7
npm ERR! 
npm ERR! Failed at the geojs@0.5.0 postinstall script 'bower --quiet install'.
npm ERR! This is most likely a problem with the geojs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --quiet install
npm ERR! You can get their info via:
npm ERR!     npm owner ls geojs
npm ERR! There is likely additional logging output above.
minerva@0.1.0 /home/travis/build/girder/plugins/minerva
└─┬ JSONPath@0.10.0 
  └── underscore@1.8.3 

I ran `npm install` on my dev machine (Ubuntu 14.04, and no doubt some other env differences from Travis), and got

>bower bootswatch#~3.3     invalid-meta bootswatch is missing "main" entry in bower.json

though `npm install` completed successfully for me.

This is a known, but [unresolved issue](https://github.com/thomaspark/bootswatch/issues/324), and I can't tell if this is even the issue I'm facing on Travis.

Any advice?

**Comment by jbeezley** [comment]
I also get an error running locally.  I don't think it is related to bootswatch.  I'll look into today.
