### ISSUE TITLE
Clean up jobs boilerplate

### ISSUE THREAD

**Issue by danlamanna** [Kitware/minerva#156]
Running a local job in Minerva currently requires a lot of boilerplate that could be reduced by abstracting  the common functionality in the `run` functions among workers, see for example [here](https://github.com/Kitware/minerva/blob/c3c60c528e1d96493a751404345a430c77250280/server/jobs/bsve_search_worker.py).

**Comment by mgrauer** [comment]
As part of that boilerplating, it may be possible to provide a sufficient abstraction to allow an easy switch from a local job to romanesco.  At least keep this in mind when writing the boilerplate, probably writing these methods with reasonably high granularity might help, or maybe just keeping track of the general operations we need for local jobs and how that would have to change for romanesco is sufficient.  

E.g., 

  * local jobs use model code, romanesco needs to use the girder client
  * local jobs can use the minerva config, need a way of getting this to a romanesco job, such as for decrypting

**Comment by mgrauer** [comment]
[Consider using Romanesco's tmpdir context manager](https://github.com/Kitware/minerva/pull/174#commitcomment-14285674)

**Comment by matthewma7** [comment]
Outdated.
