### ISSUE TITLE
Add ability for SourceModel subclasses to register themselves

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#160]
#159 provided some prefactoring to make it easier to add a new SourceModel subclass.

When adding a new SourceModel subclass a developer still needs to

  * add the source_type to the SourceCollection.model function switch
  * add the icon action event handler to SourcePanel and specify a widget
  * add itself to the dictionary of sourcetypes held in SourcePanel
  * add its creation widget to the dictionary in AddSourceWidget

Ideally some registration method should be provided that can set all of these properties at one time.

Maybe a method on the minerva application object?  And when a developer defines a new SourceModel subclass, in that same source file there could be an immediate that registers the subclass with the minerva application object.  This provides some ability to define client side code outside of minerva and have it imported into minerva simply by enabling another girder plugin (assuming minerva's core template loads only client side code from enabled plugins, which is a good change anyway).

I'd love to hear any other good ideas or potential problems with this approach.

**Comment by mgrauer** [comment]
A required part of this will be updating the "add a source" documentation.

**Comment by danlamanna** [comment]
I think this is the sort of approach we've been thinking about for all of the client-side code in Minerva (read: plugin system), not just source models.

I think using the Minerva application object as a sort of registry makes sense. In fact, other girder plugins could have their own gruntfile namespacing jade/stylus files as ```my_own_plugin.templates``` so all the client-side code could be self-contained.

**Comment by aashish24** [comment]
> I think this is the sort of approach we've been thinking about for all of the client-side code in Minerva (read: plugin system), not just source models.

Agree. @mgrauer your approach sounds good to me. Having registry within the minerva application object is good as well. I don't have much to add.

**Comment by mgrauer** [comment]
I agree this is desirable for all the client-side code, but sources are closest to having the api defined cleanly enough.  What's nice is by making it easier to add new sources within Minerva this way, we also enable the ability from plugins.

Analyses would probably be next.  

Datasets would be harder, as you'd have to also add some ability to render a new type that Minerva wasn't aware of.  Changes to support #157 can enable this.

**Comment by aashish24** [comment]
> Analyses would probably be next.

I was thinking the same that Analysis can be dealt in very similar way. 

> Datasets would be harder, as you'd have to also add some ability to render a new type that Minerva wasn't aware of. Changes to support #157 can enable this.

I think what we need is readers that can read datasets and convert them into features or layers. For example, a GeoJSON can be read by geojson reader and coverts them into features which then can be added a a new layer or existing layer. In case of WMS dataset, it is mostly likely be a new layer altogether.

**Comment by mgrauer** [comment]
Two other approaches to consider

  * wrapping views from plugins
  * responding to UI issued events

**Comment by mgrauer** [comment]
Related, see [this comment](https://github.com/Kitware/minerva/pull/174#discussion_r44318814) from @danlamanna .

**Comment by mgrauer** [comment]
This is moot now, Sources are being killed off, at least in terms of the client side Source Model and Source Panel.

see https://github.com/Kitware/minerva/issues/275
