### ISSUE TITLE
local source uploader

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#162]
In the source panel, add the ability to upload a local (client side) file as a source.

See [here](https://github.com/Kitware/minerva/pull/159#issuecomment-149896160) for some details.

A lot of the code to do this already exists in the codebase, at least in the history.

**Comment by mgrauer** [comment]
relates to [create new geojson dataset from upload ](https://github.com/Kitware/minerva/issues/101) as well

**Comment by danlamanna** [comment]
+1 - One of our collaborators mentioned having this exact feature earlier this week. @aashish24

**Comment by mgrauer** [comment]
@danlamanna Do you have any more specifics?

**Comment by danlamanna** [comment]
Nothing outside of what you're already doing (I assume).

Ideally we would just be able to upload a file as a source (girder item) that we could use as an input to other analyses.

I believe this is exactly how the local filesystem data**set** works currently.

**Comment by mgrauer** [comment]
Until #159 gets merged anyway.  That PR removes the dataset upload.  :no_entry_sign:

**Comment by mgrauer** [comment]
PDF will be the first filetype supported on the local uploader.

**Comment by aashish24** [comment]
@mgrauer this one is done so closing it now.
