### ISSUE TITLE
Allow users to set default view (s)

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#164]
For now, we only have one view (map). What we need is the ability to set default view for a user in a session.

**Comment by danlamanna** [comment]
Can you flesh out what other type of views there will be, and how they will be rendered?

**Comment by aashish24** [comment]
@danlamanna in short term, there will be a PDF view for instance. 

> how they will be rendered?
Can you explain what you mean here by how? It could depend on the type of the dataset and how we are going to to approach to support views in general.

**Comment by aashish24** [comment]
no longer valid.
