### ISSUE TITLE
Enable minerva for non-admin users

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#165]
Look over #144 for details, but use a different approach.

Currently only admin users can use Minerva, and we are abusing GET requests by creating folders.

Change the approach to dealing with users to be the following

  * when Minerva is enabled as a plugin
    * create a `minerva` collection and a `minerva` group granting read access to that collection
    * create an `analysis` (es?) folder under the `minerva` collection
    * for any existing user
      * create a `minerva` folder under their user
      * create a `dataset` folder under the user `minerva` folder
      * create a `session` folder under the user `minerva` folder
      * create a `source` folder under the user `minerva` folder
      * add the user to the `minerva` group
  * when a new user is added and Minerva is already enabled, listen to the user creation event and follow the above procedure to enable the user for Minerva
  * figure out details related to running romanesco
      * maybe add the user to the list of enabled romanesco users
      * more ideally tie this into the `minerva` group
      * this may involve tying in the `minerva` collection `analysis` folder

**Comment by aashish24** [comment]
http://www.datamation.com/imagesvr_ce/2498/keynesian-coding.jpg

**Comment by mgrauer** [comment]
Also #71.

**Comment by aashish24** [comment]
@mgrauer this is a critical one I think.

**Comment by aashish24** [comment]
#71
