### ISSUE TITLE
Deleting session and recreating new one results in getting the same deleted session. 

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#172]

**Comment by aashish24** [comment]
Steps to reproduce:

1) Create a session
2) Add a new sources / dataset
3) Delete the session
4) Create a new session with a different name

**Comment by mgrauer** [comment]
@aashish24 I just tried to reproduce this and could not.

I had added a new dataset to the session and didn't save the session, then deleted the session and created a new session.  The dataset was not part of the new session.

I also tried this and did save the session before deleting.  Again the dataset was not part of the new session.

If you still see this, can you check that you are on master and then provide more detail about whether you are adding the dataset to the map or not, whether you are saving the session before deleting it, and what exactly you are seeing in the newly created session?

**Comment by aashish24** [comment]
Sure.. will do. thanks @mgrauer

**Comment by aashish24** [comment]
I am closing it now since I wasn't able to reproduce it.
