### ISSUE TITLE
Allow for geojson points to cluster in Map display

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#173]
See issues in #143.

**Comment by danlamanna** [comment]
Depending on how #157 is implemented, I can see us having renderers which can be inherited - one of which could be a very basic "take these columns for x and y" and plot the clusters on the map, for others to extend.

I have [some clustering code](https://github.com/Kitware/minerva/pull/122/files#diff-d842a6ee85c22afe43dda555deda7c34R117) to do this, but it's hardly more than the jsbin @jbeezley set up when he introduced it.

**Comment by matthewma7** [comment]
Outdated.
