### ISSUE TITLE
WMS source list does not present where data is raster or vector

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#178]
* It would be nice if in the list, user's would know whether the dataset is a raster or a vector dataset

**Comment by mbertrand** [comment]
@aashish24 I could do this for EpiGeo but there is no guaranteed reliable way to determine this from all WMS servers.  For EpiGeo, all the raster layers include 'WCS' as a keyword.  However, other WMS servers don't include this keyword, or contain no keywords at all.

**Comment by aashish24** [comment]
@mbertrand I was thikning we can query GetCapabilities and check for formats but that would be valid only if the format is for example geojson for vector tiles. Currently we only have raster. Once we have vector tiles, then this feature would be useful.

**Comment by mbertrand** [comment]
@aashish24 WMS GetCapabilities doesn't necessarily provide that information.  WMS provides image-based map tiles for both vector and raster data.  You could do a WFS GetCapabilities to only get a list of vector layers, then a WCS GetCapabilities to only get a list of raster layers, again assuming the remote server supports them.  Right now minerva is using WMS GetCapabilities which returns both raster and vector layers.

**Comment by aashish24** [comment]
thanks @mbertrand in that case, let's close this issue
