### ISSUE TITLE
Deduplicate template code using jade blocks

### ISSUE THREAD

**Issue by danlamanna** [Kitware/minerva#179]
Widgets and panels share a lot of common jade code, at a minimum they tend to share the same format, for example:
[sourceInfoWidget.jade](https://github.com/Kitware/minerva/blob/68f0ef4fd7ff4686a8f81fb8525b100ef0889ef2/web_external/templates/widgets/sourceInfoWidget.jade)
[datasetInfoWidget.jade](https://github.com/Kitware/minerva/blob/68f0ef4fd7ff4686a8f81fb8525b100ef0889ef2/web_external/templates/widgets/datasetInfoWidget.jade)

These could be abstracted using [jade's inheritance](http://jade-lang.com/reference/inheritance/) capabilities.

**Comment by matthewma7** [comment]
Outdated.
