### ISSUE TITLE
API keys get rate limited

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/minerva#18]
Every time the app is loaded somewhere, one connection to the twitter API is opened.  If enough people open the app, or if one person reloads enough times, the key's rate limit will be hit, resulting in the app working ok but not producing any data.

It's murky how to get around this.  For demo days, etc., we can have @aashish24 regenerate his tokens so they are fresh, and this should cover the demo period.

In the longer run it may be that we need to just cache a single stream within the streaming service.  Each person requesting a Tangelo stream of tweets will be getting data from a single Twitter stream.  It's not obvious how to do this but it should be possible.

**Comment by mgrauer** [comment]
Closing this as it referred to an earlier incarnation, but a different app.

ping @ronichoudhury In case you need this info.
