### ISSUE TITLE
specify Session state more precisely

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#183]
do it

**Comment by danlamanna** [comment]
It seems like between this, #184, #185, and #207 there needs to be some fleshing out of per-session configuration, what it will contain, and what can be overridden from a permalink.

What to store per session:
- Layout   
 - Panels   
   - State per panel (collapsed, so on)
- GeoJS attributes
 - Basemaps, center, zoom, layers on the actual map

Additionally, individual plugins should be able to store whatever they want. More complicated maps come to mind, which can be demonstrated in the Taxi App (look at this [url](http://demo.kitware.com/minerva/#mapview?general-display=ga-tile-set%3Dmqsat%26ga-tile-opacity%3D0.5&taxi-display=ga-show-taxi-data%3Dtrue%26ga-display-type%3Dpickup%26ga-display-process%3Draw%26ga-display-max-points%3D910000%26ga-display-max-lines%3D10000%26ga-display-num-bins%3D15%26ga-data-opacity%3D0.1&panels=ga-anim-settings%3Dtrue&general-filter=ga-region%3D&map=x0%3D-74.2125168%26y0%3D40.8461341%26x1%3D-73.7317581%26y1%3D40.6590970%26zoom%3D12.45)).

**Comment by mgrauer** [comment]
I'm glad you highlighted this.  I agree with you that the session should have these two aspects, and the base map attributes should be part of the Map state, rather than the layout.  I alluded to that in https://github.com/Kitware/minerva/issues/157#issuecomment-157896899 but didn't split it out clearly enough.
