### ISSUE TITLE
Reduce clicks in add source widget

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#194]
This is a usability issue, it would be nice to click just once on the source type and go to the next screen.  Either a button on the source type, or when a radio button is selected, or a dropdown, upon selection of any of these, the add source widget specific to the selected type should be presented.

See [this comment](https://github.com/Kitware/minerva/pull/174#discussion_r44317616).

**Comment by aashish24** [comment]
Ref: #71

**Comment by matthewma7** [comment]
Outdated.
