### ISSUE TITLE
Create a generic analysis widget, or at least a hierarchy input to an analysis widget

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#196]
See [this comment](https://github.com/Kitware/minerva/pull/174/files#r44320083).

We also have a common pattern of an analysis with a name and a textbox, and the textbox could optionally validate as JSON.

**Comment by matthewma7** [comment]
Gaia analysis has been integrated into Minerva as a dependancy, and its analysis has been set to be exposed. The concept of plugin and play analysis is outdated.
