### ISSUE TITLE
Ease deployment for development, specifically for support of Romanesco

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#199]
It is a lot of work and pain to get Romanesco going in Minerva, and this could definitely turn off collaborators and other developers.  It would be nice to split out support for Romanesco within Minerva to  a separate plugin.  This would also mean separating out the existing Romanesco analyses to this plugin or some other project specific plugins.

**Comment by aashish24** [comment]
@mgrauer would it be a minerva plugin? Also, what are the main issues?

**Comment by mgrauer** [comment]
@aashish24 

I'm not sure, and plugin may be the wrong word.  See #176 for details.

**Comment by jbeezley** [comment]
There is room to make romanesco easier to deploy for development.

* Copying the config file can (and should) be made automatic (or unnecessary)
* We can improve `girder-install` to do most of the installation work

Starting up the romanesco worker is more complicated.  In production, it should go on another host so we don't really want to make the local setup automagic.  Maybe we can raise an issue in Romanesco about making the deployment and configuration easier.

**Comment by mgrauer** [comment]
@jbeezley 

Thanks, making Romanesco easier to deploy for dev, especially as a Girder plugin rather than just the python package subdir, would help greatly.

I think for development we would want Girder and Minerva git cloned.  Would `girder-install` be available given that, since we didn't `pip`?

**Comment by jbeezley** [comment]
One of my intentions was to make `girder-install` capable of installing from a git repository.  It will currently install the plugin's `requirements.txt` file, but we could also make it run `setup.py develop` when `setup.py` exists.  My goal would be to make the CLI look like this:

```
girder-install plugin kitware/romanesco --with spark
```
At that point, you would need another step to start up the romanesco client somehow.

**Comment by jeffbaumes** [comment]
Something like your suggested CLI would be nice @jbeezley

**Comment by mgrauer** [comment]
To rephrase, would you need to `pip` install girder to get `girder-install`?  How would that work if I wanted a git clone of girder?

I definitely like that interface you describe.

**Comment by jbeezley** [comment]
To put `girder-install` in your path, you can either:
```
git clone https://github.com/girder/girder.git
cd girder
python setup.py develop
```
or the equivalent
```
pip install -e git+https://github.com/girder/girder.git#egg=girder
```

In the later case, the girder repo is cloned in you virtualenv under `src/girder`.

**Comment by aashish24** [comment]
@mgrauer I believe this is done?

**Comment by aashish24** [comment]
At least majority of it.
