### ISSUE TITLE
Get client+server tests working

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#202]
We had a start of this in #72, but that has aged.

Currently we have client side tests, but they don't actually test a round trip to the server.  At least some preliminary session test should be created.

**Comment by mgrauer** [comment]
Also clean up the construction of the client test HTML

>Ideally, the build task for this file should use grunt-contrib-jade with as much as possible of the template data provided statically (possibly using underscore-style templates) in the grunt config.

from https://github.com/Kitware/minerva/pull/201#issuecomment-157399228

**Comment by matthewma7** [comment]
Minerva uses Girder's test infrastructure and it's working now.
