### ISSUE TITLE
Inform developers to specify geojs version as needed

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#209]
Currently we are using some [commit](https://github.com/Kitware/minerva/blob/c7b82591415c0ee991347ba1b1762e47bf22421e/package.json#L9) of geojs, but we need to keep bumping that.

Should we track master instead?  e.g. @jbeezley just put a fix in to allow installs of minerva via girder-install using sudo.  I can bump to that commit of GeoJs or just set the ref as `master`.

At some point we may want to peg to a version of GeoJs, at least for a release of Minerva.  Similar to #204.

This could get a bit dicey for development, imagine doing work on a feature in Minerva that relies on a particular GeoJs commit.  You could change the commit of GeoJs in your local dev branch, but that would reintroduce the commit issue when merged in to Minerva master.  Or you could leave the ref as master, but then you'd have to wait until that branch is merged into GeoJs master before merging your branch into Minerva.  This isn't dependency hell, more like dependency heck.

**Comment by aashish24** [comment]
In long run using a release version would be desirable but for now, I think just sticking to a commit probably is okay since we have lot of changes happening on both end (Minerva and GeoJS). But I am open for other suggestion that may work better in our workflow.

**Comment by danlamanna** [comment]
At the moment I think Minerva is volatile enough (pre any version number at all) that we shouldn't pin it to a version of geojs. So it comes down to tracking master or pinning to a commit.

I would rather pin to a specific commit and periodically bump it when someone needs it to avoid any potential breakages in regular development.

**Comment by mgrauer** [comment]
GeoJs is having release versions much more frequently now, and we are advancing our version of GeoJs with each release.  I'll close this issue as it seems we have organically resolved it.
