### ISSUE TITLE
Add opacity slider for all layers

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#216]
Depends on support in GeoJS.  Currently we only have opacity sliders for WMS layers.

**Comment by mgrauer** [comment]
https://github.com/OpenGeoscience/geojs/issues/468

**Comment by aashish24** [comment]
Ref: https://github.com/Kitware/minerva/issues/242

**Comment by aashish24** [comment]
@mgrauer I believe this is done?

**Comment by mgrauer** [comment]
Will be with #301.

**Comment by aashish24** [comment]
Ah, I didn't realize that its not in master yet, thanks @mgrauer
