### ISSUE TITLE
Precisely define domain objects

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#221]
See [this comment](https://github.com/Kitware/minerva/pull/206#issuecomment-158503247) and follow-on comments.

Provide precise definitions of Source, Dataset, Analysis, Visualization, etc.  Decide on Provenance tracking and immutability properties of domain objects.

**Comment by mgrauer** [comment]
See [this Google Doc](https://docs.google.com/document/d/1pXWemoXEGS1G_6IrDV9Uxk2lk69oyb8F-JZAt_RliFw/edit).

**Comment by aashish24** [comment]
Nice! @mgrauer
