### ISSUE TITLE
Add progress indicators

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#222]
For long running actions, give some indication that things are happening.
- when adding a new WMS source, especially with authentication and many layers
- when adding a dataset to the map, while waiting for rendering
- when removing a dataset from the map

**Comment by aashish24** [comment]
@mgrauer I am moving this to MS 0.2

**Comment by matthewma7** [comment]
Add and removing large vector dataset is a current a thread blocking mechanism, even if we provide an indicator, we can't make animate it. Consider close.
