### ISSUE TITLE
Prevent map scrolling out past max

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#239]
Is there a way to know the max scroll value, and prevent the map from going past that?

So we don't end up with views like

![screen shot 2015-12-21 at 10 55 17 am](https://cloud.githubusercontent.com/assets/595023/11934654/828e2de8-a7d1-11e5-9fb9-603b5de1107a.png)

**Comment by jbeezley** [comment]
That is handled automatically in the current master by wrapping in X and preventing zooming out beyond the available data in Y.

**Comment by aashish24** [comment]
Ref: #167
