### ISSUE TITLE
Update wms for GeoJs 0.6

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#242]
Upgrade GeoJs to the hash of release 0.6, and change the wms layer code in accordance with https://github.com/OpenGeoscience/geojs/commit/69c8b9b2e9372902d508f63d76978978a67fedd2

**Comment by aashish24** [comment]
@mgrauer GeoJS 0.6 is out now: https://github.com/OpenGeoscience/geojs/releases/tag/v0.6.0
