### ISSUE TITLE
Setup a tile-server at Kitware

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#248]

**Comment by mbertrand** [comment]
Geoserver in data_services does this for layers in the included geonode instance.  One thing that might be nice eventually (but probably way too ambitious for 0.1 release) is having a tile-server integrated with minerva/girder that automatically creates & serves tiles for large user datasets (options include tilestache, node-tileserver, and others).

**Comment by aashish24** [comment]
@mbertrand thanks. I have a vagrant that uses tilemill, I just need to find some downtime to get it installed on the VM. tilemill performs much better than geoserver in my experience but let me know if you have other experience.

**Comment by brianhelba** [comment]
When you're ready to do any direct integration with Girder / Minerva on the server-side, please let me know. I'm working on the [``large_image`` plugin](https://github.com/DigitalSlideArchive/large_image) for Girder, which provides, among other things, a fully integrated HTTP tile server. I'd like ``large_image`` to have support for both geospatial data sources and geospatial HTTP protocols (currently it's focused on microscopy images), and this would be a great opportunity.

**Comment by aashish24** [comment]
Sure @brianhelba. Currently I am working dealing with deploying vm's at Kitware. It is mostly related to procedure and security related. I think we are making good progress and I am hoping that we will have some solution in near future (a month timeframe).
