### ISSUE TITLE
Unmet plugin dependencies

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#249]
With latest checkout of girder and Minerva, I am getting unmet dependencies: (Message below). But no-where (at least in my quick look), I could find what I missing., 

Minerva Geospatial ApplicationVersion 0.1.0EXPERIMENTAL
An application for geospatial analytics.
This plugin has unmet dependencies.

**Comment by mgrauer** [comment]
@aashish24 when do you see this?  from git?  pip?  python -m girder? npm?

**Comment by jbeezley** [comment]
My guess is that you're missing the romanesco plugin.

**Comment by aashish24** [comment]
> My guess is that you're missing the romanesco plugin.

@jbeezley you are probably right (although I thought I had it installed and setup last time). One thing was that there was no error message visible on system console or web-console. Also, Girder UI just had the message but no further information. I am wondering if we can make it more clear? May be it is a Girder issue.

**Comment by danlamanna** [comment]
You were definitely missing one or more of romanesco/jobs/gravatar. I added that message because Girder was previously throwing a KeyError backtrace in the web console.

I'll add a PR to Girder that will state the missing top level dependencies in the error message.

**Comment by aashish24** [comment]
> I'll add a PR to Girder that will state the missing top level dependencies in the error message.

@danlamanna that would be most useful! Please link it to here so that we can close this issue.

**Comment by mgrauer** [comment]
This has been merged into Girder master.  We'll get the behavior when we upgrade to Girder v1.4.2.

**Comment by mgrauer** [comment]
related to https://github.com/Kitware/minerva/issues/276

**Comment by mgrauer** [comment]
Fixed by #302.
