### ISSUE TITLE
Figure out how to store large datasets without cluttering the git repo

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#261]
See [this comment](https://github.com/Kitware/minerva/pull/256/files#r50018840).

**Comment by cpatrick** [comment]
I strongly recommend [CMake External Data](https://cmake.org/cmake/help/v3.3/module/ExternalData.html)

**Comment by jbeezley** [comment]
@cpatrick  Cool, I didn't realize that module existed.  Even as recently as a couple of months ago I was programming this exact functionality by hand for another project.

However, I'm extremely hesitant to make cmake a requirement for anything outside of testing for minerva.  We are already making thing hard on ourselves by combining node and python packaging conventions.  Adding cmake to the mix will complicate things even further.

**Comment by brianhelba** [comment]
We need this exact feature for testing our [large_image Girder plugin](https://github.com/DigitalSlideArchive/large_image). I just spoke with @jbeezley , and he said that we should be able to use Girder as a backend for storing the CMake External Data, instead of the traditional Midas.

If so, and if there is any additional common logic that should be added to improve maintainability, I'd like to make sure it's able to be used from Girder / Girder plugins too.

**Comment by cpatrick** [comment]
@jbeezley yeah, I think using CMake to drive the build and package (even if it's calling grunt) would be a good way/reason to do this. That said, if you don't use CMake ExternalData, then at least implementing something consistent with it would be preferred. I'd also add that CMake is not a big dependency and is ubiquitous. I envision a future where we one-day use CPack to prepare installers (deb, rpm, etc) for our tools. :sunrise: 

@brianhelba I'd love to get the support into Girder for CMake External Data.

**Comment by brianhelba** [comment]
@cpatrick I've asked @jbeezley to start to look into implementing this just for our plugin. Anything that should to be generalized can be put upstream in Girder pretty easily, as we're developing off Girder master.

If we have to use Midas as the data store, we can, but I'd much rather use a Girder instance (in this case, [data.kitware.com](https://data.kitware.com/)).

I'll leave you Minerva folks alone now, I just want to make sure we don't implement something twice. :wink:

**Comment by matthewma7** [comment]
I believe the need for this is gone. GeoJS do pull external data without cluster repo.
