### ISSUE TITLE
Better define dependency versions of romanesco and girder

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#263]
See #259 for more details than you want.

Some details:

  * We should more clearly pin to a Girder version, and define this in our docs, our travis and have this as the default `girder_version` in our site.yml for ansible
  * We should do similar for Romanesco, but that will additionally depend on Romanesco having versions that are tied to Girder and further on whatever changes (i.e. split b/w the Girder plugin part and the python package part) are in Romanesco's future

**Comment by jbeezley** [comment]
I would add we should have a general policy of making sure Minerva always works on the most recent release of all of its dependencies, including Girder.  To go with this, we should set up a nightly dashboard that tests against the latest versions on PyPI.  I can set this up on my machine the same as I did for Girder.

**Comment by mgrauer** [comment]
related to https://github.com/Kitware/minerva/issues/276

**Comment by mgrauer** [comment]
Closed by #302.
