### ISSUE TITLE
Error when clicking on WMS visualization

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#266]
I think this was introduced by the MMWR info click work recently, and I noticed it when bringing in GeoJs 0.6.0 (so be sure to have #265 merged in to test).

If you have any WMS layer visualized, if you click on the map, you'll get the following error in the javascript console.

> WMSFeatureInfoWidget.js:81 Uncaught TypeError: Cannot read property 'll2m' of undefined

**Comment by mgrauer** [comment]
#265 has been merged.

**Comment by jbeezley** [comment]
That looks like an error caused by GeoJS 0.6 actually.  Did you rerun `npm install` after switching branches?

**Comment by jbeezley** [comment]
I see the other branch was merged.  I can fix this pretty quickly.
