### ISSUE TITLE
Add client side testing (unit testing) support or make it better

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#267]

**Comment by aashish24** [comment]
@jbeezley will add a more substantial unit-testing test for the client-side

**Comment by jbeezley** [comment]
@manthey reminded me that GeoJS master already has the capability to fall back to another renderer when webgl isn't present.  


For this issue, I will plan to do the following:
* Update GeoJS to bring in the fallback renderer mechanism
* Try to get some rudimentary code coverage reporting working
* Add a test that makes an assertion on the state of the map to show

Ultimately, I think we need address the issues discussed in https://github.com/Kitware/minerva/issues/271 to integrate more closely with girder's testing infrastructure.  I would like to make use of (and extend) things like [`girderTest`](https://github.com/girder/girder/blob/master/clients/web/test/testUtils.js) as much as possible to avoid duplicating a lot of effort, but this is beyond the scope of this issue.

**Comment by aashish24** [comment]
Thanks @jbeezley These all sounds good to me. Let's find some time for girderTest.

**Comment by mgrauer** [comment]
Fixed by #267.
