### ISSUE TITLE
Update support for contour json based on geojs 0.6.0

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#272]
Support for contour json seems to have changed in geojs 0.6.0.  The [example](http://opengeoscience.github.io/geojs/examples/contour/doc/main.html) no longer uses a 'contourJsonReader', and contour json no longer renders.  Update Minerva accordingly.

**Comment by jbeezley** [comment]
I looked at this briefly.  The [contourJsonReader](https://github.com/Kitware/minerva/blob/7d6cc432a2226de7277b622382cd0d4687e102cd/web_external/js/contourJsonReader.js) is an extension to geojs defined by minerva.  I don't see anything in that should have been affected by any geojs updates.

**Comment by mgrauer** [comment]
Thanks for looking into it @jbeezley . I'll dig in more later on.

**Comment by mgrauer** [comment]
Fixed by #257.
