### ISSUE TITLE
Unify map container layer feature info presentation

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#275]
The choropleth and WMS layers present feature info in separate dialogs.  Let's unify these into a standard panel that is part of the map container.

See #274  for more.

**Comment by jbeezley** [comment]
Agreed.  I tried to create the new [`ClickInfoWidget`](https://github.com/Kitware/minerva/blob/master/web_external/js/views/widgets/ClickInfoWidget.js) to be extensible.  It should be fairly straightforward to migrate the WMS widget to extend this class.

**Comment by aashish24** [comment]
> The choropleth and WMS layers present feature info in separate dialogs. Let's unify these into a standard panel that is part of the map container.
> 
> See #274 for more.

+1

**Comment by matthewma7** [comment]
The current code base has a unified popup window for different layers.
