### ISSUE TITLE
Better namespacing and self description of JS events

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#279]
This issue is intended to solicit feedback.  If we arrive at a proposal it could be implemented at the same time as #278.

After seeing the entire catalog of Girder JS events, I'm thinking we can learn from this and make our JS events a little more self describing, since we haven't had a release yet that establishes an official API surface.

Here are two examples. 

`m:datasetCreated` is a current event, errrr, an event we have currently.  How about instead `minerva:dataset.created`?

`m:geoDataLoaded` is an event proposed in a PR, for when a dataset has loaded its geo related data.  Instead `minerva:dataset.geo.dataLoaded`?  or `minerva:dataset.geo_dataLoaded`?

**Comment by matthewma7** [comment]
The current code base is gradually transitioning to a promise based async execution pattern, away from the event-based execution flow. Close.
