### ISSUE TITLE
Make the girder version come from a single source

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#293]
see #281

**Comment by mgrauer** [comment]
this could be a girder_version in the plugin.json, but that kinda suggests a system built into girder.  so as a stop-gap it could be a separate file.

**Comment by kotfic** [comment]
+1 for putting it in plugin.json. As long as it is machine readable i think we can make this work for all the places we need it.

**Comment by danlamanna** [comment]
I'm -1 for using plugin.json, I agree it could be interpreted by others as Girder accepting such a key in its configuration. I would rather drop a `.girder-version` in the root directory to avoid confusion.

**Comment by kotfic** [comment]
+1 for .girder-version

On Fri, Feb 12, 2016 at 2:42 PM, Dan LaManna <notifications@github.com>
wrote:

> I'm -1 for using plugin.json, I agree it could be interpreted by others as
> Girder accepting such a key in its configuration. I would rather drop a
> .girder-version in the root directory to avoid confusion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/minerva/issues/293#issuecomment-183462282>.
>



-- 
Christopher Kotfila
R&D Engineer
Kitware Inc.
http://www.kitware.com/company/team/kotfila.html

**Comment by mgrauer** [comment]
works for me, should be easy to migrate should Girder provide support in plugin.json
