### ISSUE TITLE
Create views for individual datasets in datapanel

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#297]
See #290.

This should clear up the jade quite a bit in DataPanel.js, and move the utility functions created in #290 to the new DatasetView.js

**Comment by aashish24** [comment]
@mgrauer would this be in 0.1 or 0.2?

**Comment by mgrauer** [comment]
This would fit in well with the dataset refactors, so I'd like it in 0.1.0.

**Comment by aashish24** [comment]
Done, thanks.
