### ISSUE TITLE
Decide whether to render panel changes when panels are collapsed

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#300]
If the Dataset Panel is collapsed, and a dataset is added, or removed from the map, or has its order layer changed in the map, we rerender the dataset panel, which opens up the collapsed state.

Decide what to do in this case.

Perhaps we want to leave the panel collapsed but render changes, so that they are shown when the panel is expanded, or just render it again when it is expanded.

Also cover the case so that we are rendering appropriate changes when the panel is expanded, e.g. adding new datasets, removing a dataset from the layers, changing a layer order in the stack.

**Comment by mgrauer** [comment]
Possibly could be addressed at the same time as #297.

**Comment by kotfic** [comment]
IMO Panel group should delegate rendering choices to each panel,  default
functionality should be to only render the body if it is open - but that
should be easy to override if a panel needs to be re-rendered even though
it it closed.

On Sat, Feb 13, 2016 at 4:34 PM, mgrauer <notifications@github.com> wrote:

> Possibly could be addressed at the same time as #297
> <https://github.com/Kitware/minerva/issues/297>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/minerva/issues/300#issuecomment-183759627>.
>



-- 
Christopher Kotfila
R&D Engineer
Kitware Inc.
http://www.kitware.com/company/team/kotfila.html

**Comment by aashish24** [comment]
> IMO Panel group should delegate rendering choices to each panel,  default
> functionality should be to only render the body if it is open - but that
> should be easy to override if a panel needs to be re-rendered even though
> it it closed.

+1

**Comment by matthewma7** [comment]
Current view engine renders everything unconditionally by default, which has a minimal performance impact with the latest browser. With current view engine, individual components could choose its own rendering behavior. Closing.
