### ISSUE TITLE
Unify/Simplify/Improve-ify the UI controls related to sessions

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#305]
Currently, if you visit a Minerva url you get a list of existing sessions and can create a new session.

<img width="457" alt="screen shot 2016-02-15 at 8 26 11 pm" src="https://cloud.githubusercontent.com/assets/595023/13064603/666f4386-d422-11e5-875d-33ab85503762.png">

Let's try to move these functions to the /session page, then we can have just a root page.

Similarly, we should clarify the UI around saving/editing an individual session, though this may need to be broken out to a separate PR.

Functionality related to an individual session is

 * name
 * description
 * basemap
   * choice of basemap
   * zoom level
   * center
 
The following should be saved in a session, but this may not need to be reflected in the UI redesign

 * currently visualized datasets
 * any color mapping/filtering/adapter properties of the visualized dataset
 * order of datasets in the stack
 * opacity of datasets

**Comment by aashish24** [comment]
@mgrauer sounds good to me but I would mark it a low priority for now unless you think otherwise.

**Comment by mgrauer** [comment]
I wanted to specify some initial tasks for @katelynnobrien and @essamjoubori related to UI work.

**Comment by aashish24** [comment]
Roger that @mgrauer based on the timeline, I am thinking that it is 0.2?

**Comment by mgrauer** [comment]
Actually, I thought about this some more, and this should be 0.1.0.

Not to get it perfect, but at least something usable.  I want to have release 0.1.0 be something that is usable by an actual (if only theoretical) user, so this should go in.  Currently, you could not navigate your way back to the sessions list from the session page without changing the URL.

**Comment by mgrauer** [comment]
We may not get all of the session save controls in for 0.1.0, but at least the session list/delete/create UI should be part of the main (session) page.

**Comment by aashish24** [comment]
> We may not get all of the session save controls in for 0.1.0, but at least the session list/delete/create UI should be part of the main (session) page.

@mgrauer since we don't have actual users yet, I would think we should consider this one for 0.2 unless someone is asking for it. What I am thinking for 0.1 is more towards developers but if you think we can finish all of the 0.1 issues in time (including this one) then I am fine with this one in 0.1. Thoughts?

**Comment by mgrauer** [comment]
@aashish24 I want version 0.1.0 to be actually usable by a developer, even if minimally.

So I want the session save/delete/create/list in the main page for 0.1.0.

I'd also like some UI around an individual session save to be improved, but what we have there works well enough to be at least usable now.  We can make whatever improvements we have time for regarding this.

**Comment by aashish24** [comment]
> I'd also like some UI around an individual session save to be improved, but what we have there works well enough to be at least usable now. We can make whatever improvements we have time for regarding this.

Sounds good thanks @mgrauer

**Comment by mgrauer** [comment]
I'm collecting all of the updates to saving an individual session state in #225 so that this issue can be closed sooner and more cleanly.
