### ISSUE TITLE
Add the user login/register controls to the UI

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#306]
It would be easy enough to drop in Girder's.  They used to exist but were removed in an overly aggressive purge.

**Comment by aashish24** [comment]
@mgrauer should this be a low priority task?

**Comment by mgrauer** [comment]
I wanted to specify some initial tasks for @katelynnobrien and @essamjoubori related to UI work.

**Comment by aashish24** [comment]
Roger that @mgrauer

**Comment by mgrauer** [comment]
This is another one, in order to be usable we need to have login/register controls.  Currently you have to go through girder to log in.  This needs to be in 0.1.0 to be usable.
