### ISSUE TITLE
Silence WMS fetch messages

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#307]
On console, I am getting tons of tons of messages for wms fetch. Is this really necessary to be ON by default @mbertrand @mgrauer 

7.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
127.0.0.1 - - [16/Feb/2016:13:22:42] "GET /wms_proxy/http:%2F%2Fgeodata.epidemico.com%2Fgeoserver%2Fwms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=geonode%3Aworldcensus_2000_ybf&STYLES=&BBOX=10018754.171394622%2C-20037508.342789244%2C20037508.342789244%2C-10018754.171394622&WIDTH=256&HEIGHT=256&FORMAT=image%2Fpng&TRANSPARENT=true&SRS=EPSG%3A3857&TILED=true&minerva_credentials=gAAAAABWOnqrKd3qjId0adbrIy9-tv15OCoHgFmRX8u9eH70sdxT07pKMNgU1de2_0FnAfOAPNZUP2OGdLdRYtqt2QyVkIMxDGoZT7VmTx1vECKSjAhM0f4%3D HTTP/1.1" 200 1784 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
127.0.0.1 - - [16/Feb/2016:13:22:42] "GET /wms_proxy/http:%2F%2Fgeodata.epidemico.com%2Fgeoserver%2Fwms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=geonode%3Aworldcensus_2000_ybf&STYLES=&BBOX=-10018754.171394622%2C-20037508.342789244%2C0%2C-10018754.171394622&WIDTH=256&HEIGHT=256&FORMAT=image%2Fpng&TRANSPARENT=true&SRS=EPSG%3A3857&TILED=true&minerva_credentials=gAAAAABWOnqrKd3qjId0adbrIy9-tv15OCoHgFmRX8u9eH70sdxT07pKMNgU1de2_0FnAfOAPNZUP2OGdLdRYtqt2QyVkIMxDGoZT7VmTx1vECKSjAhM0f4%3D HTTP/1.1" 200 1784 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"

**Comment by matthewma7** [comment]
Tried to reproduce the behavior, didn't find it in production. Closing.
