### ISSUE TITLE
Find ways to optimize sending GeoJSON data between client/server

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#313]
Ref: https://github.com/mapbox/geobuf

**Comment by aashish24** [comment]
Ref: https://github.com/Kitware/minerva/issues/269

**Comment by brianhelba** [comment]
Ping @manthey . This is relevant to the work he's doing with the HTTP API for vector annotations (which is a cousin dialect of GeoJSON). Also, those annotations will be rendered with GeoJS.

**Comment by jbeezley** [comment]
Also, [tippecanoe](https://github.com/mapbox/tippecanoe) for tiling geojson datasets.

**Comment by matthewma7** [comment]
Based on latest development and discussion, sending large geojson is not ok, but visualizing large geojson is the issue. The current industrial trend is vector tile. Closing this.
