### ISSUE TITLE
Create minerva.js

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#329]
Figure out a roadmap to making Minerva's components available in smaller chunks, e.g. so you don't have to install Spark to get some client side panels.

The first of these that makes sense is to create client side components.  These may end up being a Girder plugin or more like an npm package, with JS and CSS.  It's hard to see how this could be used by anything that isn't running with the Girder client libraries near term.

The outcome of this issue should be a document with details saying how to split up (at least) the client side components of Minerva for easy ingestion.  A similar plan for the server side would be great.

This relates to https://github.com/Kitware/minerva/issues/273.

**Comment by matthewma7** [comment]
This is outdated. Close.
