### ISSUE TITLE
Clean up library packaging and inclusion

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#33]
Right now the libraries are a mess in inputs, in that some come from cdns, some are included in the source of the project, some come from npm.  They are also a mess in outputs, in that some are packaged together and some separately--though there are some tricky issues here in terms of loading order.  Also, there are libs and css files from experiments that maybe should not be included in a released version.

Before a first release, this should be addressed.

**Comment by jbeezley** [comment]
Good point.  We might think about going with something like [webpack](http://webpack.github.io) to bundle everything together.

**Comment by cjh1** [comment]
+1 for webpack, have used it on  a couple of other projects.

**Comment by mgrauer** [comment]
Related, we now store the full list of JS dependencies in two places

  1. https://github.com/OpenGeoscience/minerva/blob/master/Gruntfile.js
  2. https://github.com/OpenGeoscience/minerva/blob/master/server/loader.py

It would be nice to have a single source and be a bit DRYer.

**Comment by aashish24** [comment]
I am in favor of doing it on 0.2.0 unless i hear otherwise.

**Comment by mgrauer** [comment]
This has been much improved with #277.

CSS side could be improved, and webpack still might be an option.

0.2.0 sounds good.

**Comment by aashish24** [comment]
@matthewma7 I think this is obsolete?

**Comment by matthewma7** [comment]
@aashish24 Yes, this is obsolete. We are using Webpack based building framework provided by girder.
