### ISSUE TITLE
Vagrant provision wipes away changes in worktree

### ISSUE THREAD

**Issue by danlamanna** [Kitware/minerva#333]
Note: This only applies if using the shared folders options.

I think [this play](https://github.com/Kitware/minerva/blob/82e3c19a851258fb1f4931d3dff5cdb5d2b9e242/ansible/roles/minerva/tasks/main.yml#L7) is the cause of the issue.

If you've mounted `{{ minerva_install_root }}`, re-provisioning will wipe away any changes you have in your working directory because of the `force=yes`. Using `force=no` will make the provisioning halt if there are any changes.

**Comment by matthewma7** [comment]
The issue seems outdated. Closing for now.
