### ISSUE TITLE
Some UI suggestions

### ISSUE THREAD

**Issue by dorukozturk** [Kitware/minerva#357]
On the main Minerva App home screen there are 5 tabs on the left hand side of the screen (Analyses, Sources, Datasets, Session Layers and Jobs).

I believe there can be better abstraction between "Session Layers" and "Datasets". I think everything that is about visualizing the datasets such as toggling the layer on and off, changing the opacity, color scheme etc. should be on the "Session Layers" tab. I think in the GIS world natural tendency is to click on the same button while toggling the layers on and off. My proposal is to move the eye button completely to the "Session Layers" and I believe it should work like a checkbox. 

Please see the document:
https://docs.google.com/a/kitware.com/document/d/1wllIZ9iM9VdaU4zfe4odKCdwBwXZHFSh4x4-M5iza1w/edit?usp=sharing

**Comment by kotfic** [comment]
:+1: this feels like a more common/ArcGIS workflow
