### ISSUE TITLE
Create useful and movable legend for continuous/discreet/shapes

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#396]

**Comment by aashish24** [comment]
@danlipsa would be nice to address this next as we have discussed.

**Comment by danlipsa** [comment]
@aashish24 Sounds good. I'll start working on it in about a week.

**Comment by matthewma7** [comment]
Closed by https://github.com/Kitware/minerva/pull/441. Though it's not movable because it's created as a GeoJS UI layer.
