### ISSUE TITLE
Layer mismatching issue

### ISSUE THREAD

**Issue by matthewma7** [Kitware/minerva#398]
When a session containing more than one layer loaded, the layers in layer panel would mismatch what's on the map.
See screenshot for detail.

![2017-04-25_12-39-15](https://cloud.githubusercontent.com/assets/3123478/25397041/e401240c-29b4-11e7-8fa7-87cf96071b44.gif)

**Comment by dorukozturk** [comment]
@matthewma7 Should we close this issue?

**Comment by matthewma7** [comment]
Totally, the issue is fixed now. I'll close this now. Thanks! @dorukozturk
