### ISSUE TITLE
Multipolygon does not show up in Minerva when using dataset from Postgres

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#404]
@matthewma7 ping @manthey, me, or @jbeezley if you need second pair of eyes.

**Comment by matthewma7** [comment]
False alarm. It was the data that is not correctly formatted at all.

**Comment by aashish24** [comment]
great, did we fix the data formatting issue then>?

**Comment by matthewma7** [comment]
@aashish24 The problem was the data that I grab off the internet somewhere, the code is good. 😄

**Comment by aashish24** [comment]
sounds good. thanks for clarification.
