### ISSUE TITLE
Think about prefixing out REST endpoints with /minerva rather than using unscores ...

### ISSUE THREAD

**Issue by cjh1** [Kitware/minerva#42]
We currently have /minerva_analysis, /minerva_dataset, /minerva_session ...

I think the following would be cleaner ...

/minerva/analysis
/minerva/dataset
/minerva/session

**Comment by aashish24** [comment]
> We currently have /minerva_analysis, /minerva_dataset, /minerva_session ...
> 
> I think the following would be cleaner ...
> 
> /minerva/analysis
> /minerva/dataset
> /minerva/session

+1

**Comment by kotfic** [comment]
+1

On Mon, Feb 15, 2016 at 10:00 PM, Aashish Chaudhary <
notifications@github.com> wrote:

> We currently have /minerva_analysis, /minerva_dataset, /minerva_session ...
>
> I think the following would be cleaner ...
>
> /minerva/analysis
> /minerva/dataset
> /minerva/session
>
> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/minerva/issues/42#issuecomment-184490925>.
>



-- 
Christopher Kotfila
R&D Engineer
Kitware Inc.
http://www.kitware.com/company/team/kotfila.html

**Comment by cjh1** [comment]
This is currently not possible with Girder ( related to the swagger version ).

**Comment by aashish24** [comment]
@matthewma7 I believe we are using minerva_ prefix to get around this?

**Comment by matthewma7** [comment]
@aashish24 Yes, we are using the minerva_ prefix.

**Comment by cjh1** [comment]
@aashish24 FYI you can now have a endpoint prefix in Girder, [see here for details](http://girder.readthedocs.io/en/latest/plugin-development.html?highlight=Prefix)
