### ISSUE TITLE
create csv => geojson conversion on the server side

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#45]
currently this is only implemented in javascript; the web client converts csv to geojson.  probably the csv mapper is broken now also.

Probably a better idea would be to have a unified stream geojson creator on the server, which can take in json or csv along with a mapping, and create geojson. This further depends on design decisions for storing features in mongo. Do we store as json or geojson?

**Comment by aashish24** [comment]
> Probably a better idea would be to have a unified stream geojson creator on the server, which can take in json or csv along with a mapping, and create geojson. This further depends on design decisions for storing features in mongo. Do we store as json or geojson?

If we run mapping on csv, then I would save geojson on the server side.

**Comment by matthewma7** [comment]
Outdated. Not in current roadmap.
