### ISSUE TITLE
Update jsonpath js dependency

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#46]
Current version is 0.10.0, update to v 0.11.0 as that changes the name of the eval function to evaluation, so we don't need to do jshint exceptions. V 0.11.0 isn't in npm yet though.

**Comment by mgrauer** [comment]
Hopefully this will be easy.  jsonpath 0.11.2 is in npm now.

https://www.npmjs.com/package/JSONPath

Likely we only need to change [package.json](https://github.com/Kitware/minerva/blob/492345daa493e25ea052d92e97d7eafcea712a42/package.json#L8) and [these two examples of jsonpath eval](https://github.com/Kitware/minerva/blob/8b6afbed829218be5ca09d578fc36c90436af080/web_external/js/views/widgets/KeymapWidget.js#L44-L52).

Do this after the eslint PR #291 goes in.

**Comment by jbeezley** [comment]
> (This package is being moved to "jsonpath-plus" to avoid npm problems in dealing with upper-case packages.)

You should probably go with `jsonpath-plus`.

**Comment by mgrauer** [comment]
I tried the last two releases of jsonpath-plus, 0.14.0 and 0.13.0.  Neither worked when run through our minifier.  I could use the un-minified version, which is 18k compared to 8k minified.

I'd rather punt this to 0.2.0.  I don't think we can even get to either of the places that use jsonpath right now in the UI.
