### ISSUE TITLE
create function to determine whether a dataset can be visualized

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#56]
This would make sense to be a function within MinervaModel.js that inspects the minerva metadata, as @kotfic suggested.

The line [`if dataset.geoJsonAvailable` in dataPanel.jade](https://github.com/OpenGeoscience/minerva/blob/master/web_external/templates/body/dataPanel.jade#L16) should be changed to call this new function.

**Comment by kotfic** [comment]
See: https://github.com/Kitware/minerva/blob/master/web_external/js/MinervaModel.js#L12-L26
