### ISSUE TITLE
Add type specific dataset models

### ISSUE THREAD

**Issue by kotfic** [Kitware/minerva#62]
Pull out mixed functionality in DatasetModel.js and create dataset specific models based on minerva `original_type` data.   There willl need to be types for:
- geojson
- json
  - contour-style json
  - non contour-style json
- mongo
- shapefile 
- csv
- s3

See https://github.com/OpenGeoscience/minerva/pull/54#issuecomment-127622749 for initial list of requirements

**Comment by cjh1** [comment]
This might be the time to think about the distinction between data sources and data types, in my view s3 and mongo are not data types ...

**Comment by aashish24** [comment]
@matthewma7 I think this is no longer relevant?

**Comment by matthewma7** [comment]
The current implementation is based on type metadata and this is outdated, so close now.
