### ISSUE TITLE
Cannot add multiple s3 datasets at the same time

### ISSUE THREAD

**Issue by kotfic** [Kitware/minerva#83]
Adding multiple datasets at the same time causes the second dataset to be in a paused state until the first completes.   This may be the intended behavior,  if so please close issue

**Comment by cjh1** [comment]
I think this is probably because we are using a local job for the import. The local job queue is served by a single thread so only one import can be run at a time. Moving the import to a romanesco job could solve this.

**Comment by zachmullen** [comment]
@cjh1 that's correct, the async event queue is provided as a convenience for doing stuff in the background, but is not intended for parallelism beyond that.

**Comment by kotfic** [comment]
Cool closing this down
