### ISSUE TITLE
understand romanesco install path

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#96]
@cjh1 Do we have to install Romanesco from an egg rather than pypi?

it might help with https://github.com/Kitware/romanesco/issues/143 if we could install from pypi.

**Comment by cjh1** [comment]
I don't think so, its just at the time we added romanesco as a dep we needed a version that wasn't yet released.

**Comment by jeffbaumes** [comment]
I am guessing Minerva may continue to need non-released versions of romanesco since that repo is being co-developed with this one. @aashish24 what do you think?

**Comment by jbeezley** [comment]
Yes, we will need to install from the repository.  Also, IMO best practices are to develop using `setup.py develop` rather than setting `PYTHONPATH`.

**Comment by aashish24** [comment]
@jeffbaumes yes, we would like to use the master as much as possible as we add new functionality to romanesco.

**Comment by mgrauer** [comment]
We are recommending to install from Git, and have removed Romanesco from requirements.txt.

See #176.
